import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";
import { fetchWooCommerceProducts } from "../utils/wooCommerceApi";
import { Product } from "../utils/wooCommerceTypes";
// Components
import ProductCard from "../components/ProductCard/ProductCard";

interface Props {
  products: Product[];
}

const Home: NextPage<Props> = (props) => {
  // destructure props //
  const { products } = props;

  console.log("--WooCommerce Products: ", products);
  return (
    <div className={styles.container}>
      <Head>
        <title>AKA Automotive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* iVendi finance calculator script */}
        {/* <script
          src="https://newvehicle.com/widgets/lib/finance-comparator/loader.js?username=&quoteeUid=&class=&condition=&vrm=&registrationDate=&capCode=&capId=&cashPrice=&vatIncluded=&vatQualifying=&currentOdometerReading=&vehicleImageUrl=&cashDepositType=&cashDeposit=&term=&annualDistance=&dateOnForecourt=&usePersistedOptions="
          async
        /> */}
      </Head>
      <div className={styles.card_container}>
        {products.map((product) => {
          return <ProductCard product={product} key={product.id} />;
        })}
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const wooCommerceProducts = await fetchWooCommerceProducts().catch((error) =>
    console.error(error)
  );

  if (!wooCommerceProducts) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      products: wooCommerceProducts.data,
    },
    // revalidate: 60 // regenerate page with new data fetch after 60 seconds
  };
};
